### PR TITLE
build on macos, pass all tests

### PR DESCRIPTION
**Pull request by gzm55**
Pass all tests on macos, fix some warnings on clang

### CODE REVIEW

**Comment by gzm55** [comment]
> I don't understand why this is needed. I think that *stuff cannot be '\0' if we are here in the code..

when invoke as

```
echo -en "PASS\nwords..." | ./slip0039 recover
```

the last `*stuff` would be `'\0'`

**Comment by gzm55** [comment]
> there should also be a compilation #warning, it is too late to warn the user at this moment, since the secret could already be leaked

A compile time warning is added with the same message as the runtime.

**Comment by rsnel** [comment]
Mmm, due to the change in the Makefile, the build does not work.  It is caused by the "-Wp,-MD," option. Do you know a proper fix for it?

This is the error message

    cc -Wall -g -Wp,-MD, -c -o wordlists.o wordlists.c
    wordlists.c:10875:1: fatal error: opening dependency file : No such file or directory
     };
     ^
    compilation terminated.
    make: *** [Makefile:16: wordlists.o] Error 1

**Comment by gzm55** [comment]
i will test on a linux machine.
And the better way for avoiding this kind of error, maybe, introducing the ci stages (e.g. travis, github action, etc.), running `make test` for different os/arch.

**Comment by gzm55** [comment]
> Mmm, due to the change in the Makefile, the build does not work. It is caused by the "-Wp,-MD," option. Do you know a proper fix for it?
> 
> This is the error message
> 
> ```
> cc -Wall -g -Wp,-MD, -c -o wordlists.o wordlists.c
> wordlists.c:10875:1: fatal error: opening dependency file : No such file or directory
>  };
>  ^
> compilation terminated.
> make: *** [Makefile:16: wordlists.o] Error 1
> ```

#3 fixes building on both macos and linux

**Pull request merged**
